services:
  mongo.db.catalog:
    restart: always
    image: mongo:latest
    container_name: mongo.db.catalog.container
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "27030:27017"
    volumes:
      - mongo.db.catalog.volume:/data/db

  mongo.db.catalog.ui:
    image: mongo-express:1.0.2-20-alpine3.19
    container_name: mongo.db.catalog.ui.container
    restart: always
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongo.db.catalog:27017
      ME_CONFIG_BASICAUTH: false
    ports:
      - "27032:8081"
    depends_on:
      - mongo.db.catalog

  mongo.db.discount:
    restart: always
    image: mongo:latest
    container_name: mongo.db.discount.container
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "27034:27017"
    volumes:
      - mongo.db.discount.volume:/data/db

  mongo.db.discount.ui:
    image: mongo-express:1.0.2-20-alpine3.19
    container_name: mongo.db.discount.ui.container
    restart: always
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongo.db.discount:27017
      ME_CONFIG_BASICAUTH: false
    ports:
      - "27036:8081"
    depends_on:
      - mongo.db.discount

  redis.db.basket:
    image: redis:latest
    restart: always
    container_name: redis.db.basket.container
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    ports:
      - "6379:6379"
    volumes:
      - redis.db.basket.volume:/data

  redis.db.basket.ui:
    image: rediscommander/redis-commander:latest
    container_name: redis.db.basket.ui.container
    restart: always
    environment:
      REDIS_HOST: redis.db.basket
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      HTTP_USER: ${REDIS_UI_USERNAME}
      HTTP_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - "27033:8081"
    depends_on:
      - redis.db.basket

  sqlserver.db.order:
    image: mcr.microsoft.com/mssql/server:2025-latest
    container_name: sqlserver.db.order.container
    user: "root"
    restart: always
    environment:
      SA_PASSWORD: ${SQLSERVER_PASSWORD}
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver.db.order.volume:/var/opt/mssql

  postgres.db.keycloak:
    image: postgres:latest
    container_name: postgres.db.keycloak.container
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres.db.keycloak.volume:/var/lib/postgresql/data

  postgres.db.keycloak.ui:
    image: dpage/pgadmin4
    container_name: postgres.db.keycloak.ui.container
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: user-name@domain-name.com
      PGADMIN_DEFAULT_PASSWORD: strong-password
    ports:
      - "8888:80"
    volumes:
      - postgres.db.keycloak.ui.volume:/var/lib/pgadmin

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak.container
    environment:
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT_BACKCHANNEL: false
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HOSTNAME_STRICT: false
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres.db.keycloak:5432/${POSTGRES_DB}
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
    command: start-dev
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - postgres.db.keycloak

  rabbitmq:
    restart: always
    image: rabbitmq:4.2.2-management
    container_name: rabbitmq.container
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  mongo.db.catalog.volume:
  mongo.db.discount.volume:
  redis.db.basket.volume:
  sqlserver.db.order.volume:
  postgres.db.keycloak.volume:
  postgres.db.keycloak.ui.volume:
  rabbitmq_data:  